export const cityStateMap: Record<string, string> = {
    "Lahore": "punjab",
    "Lodhran": "Punjab",
    "Mangla": "Punjab",
    "Multan": "Punjab",
    "Pindi Bhattian": "Punjab",
    "Rahim Yar Khan": "Punjab",
    "Rawalpindi": "Punjab",
    "Rojhan": "Punjab",
    "Sialkot": "Punjab",
    "Karachi": "sindh",
    "Sukkur": "sindh",
    "Peshawar": "Khyber Pakhtunkhwa",
    "Abbottabad": "Khyber Pakhtunkhwa",
    "Charsadda": "Khyber Pakhtunkhwa",
    "Dera Ismail Khan": "Khyber Pakhtunkhwa",
    "Haripur": "Khyber Pakhtunkhwa",
    "Quetta": "Balochistan",
    "Islamabad": "Islamabad",
    "Gilgit": "Gilgit-Baltistan",
    "Skardu": "Gilgit-Baltistan", 
};